name: ItemCooldowns
version: '1.01'
main: net.mattwhyy.ItemCooldowns.ItemCooldowns
api-version: '1.19'
authors: [ mattwhyy ]
description: Allows you to easily set a cooldown for any item
commands:
  setcooldown:
    description: Set a cooldown for an item
    usage: /setcooldown <item> <seconds>
    permission: itemcooldowns.set
    permission-message: You do not have permission to use this command.
  resetcooldown:
    description: Reset all cooldowns for the player
    usage: /resetcooldown
    permission: itemcooldowns.reset
    permission-message: You do not have permission to use this command.
  getcooldown:
    description: Check the current cooldown of an item
    usage: /getcooldown <item>
    permission: itemcooldowns.get
    permission-message: You do not have permission to use this command.
permissions:
  itemcooldowns.set:
    description: Allows setting item cooldowns
    default: op
  itemcooldowns.reset:
    description: Allows resetting all cooldowns
    default: op
  itemcooldowns.get:
    description: Allows checking an item's cooldown
    default: op
